### ISSUE TITLE
Wrong code generation (check_len) with bert_javascript

### ISSUE THREAD

**Issue by xafizoff** [synrc/bert#24]
I got a `json-bert.js` which contains
``` javascript
function check_len(x)  { try { return (eval('len'+utf8_arr(x.v[0].v))() == x.v.length) ? true : false }
                         catch (e) { return false; } }
```
From `utf8.js`:
``` javascript
function utf8_arr(ab) { if (!(ab instanceof ArrayBuffer)) ab = new Uint8Array(utf8_enc(ab)).buffer;
                        return utf8_dec(ab); }
```

This function always fails because utf8_arr expects as its input an ArrayBuffer. But `bert.js`s `atom(o)` gives an `Uint8Array` as `v` property.

Possible fix: replace `utf8_arr(x.v[0].v)` with `utf8_arr(x.v[0].v.buffer)` or `utf8_dec(x.v[0].v)`.

Or am I getting something wrong?

**Comment by 5HT** [comment]
Yeah, seems like the first candidate is true `utf8_arr(x.v[0].v.buffer)`
